import watchImg1 from "../../assets/images/products/watches/elegant_black_watch.webp";
import watchImg2 from "../../assets/images/products/watches/classic_silver_watch.jpg";
import watchImg3 from "../../assets/images/products/watches/sporty_digital_watch.jpeg";
import watchImg4 from "../../assets/images/products/watches/gold_luxe_watch.webp";
import watchImg5 from "../../assets/images/products/watches/leather_strap_watch.jpg";
import watchImg6 from "../../assets/images/products/watches/smart_fitness_watch.jpg";
import watchImg7 from "../../assets/images/products/watches/vintage_style_watch.jpg";
import watchImg8 from "../../assets/images/products/watches/blue_dial_watch.webp";
import watchImg9 from "../../assets/images/products/watches/rose_gold_watch.jpg";
import watchImg10 from "../../assets/images/products/watches/apple_watch_ultra_2_black_akrales.jpg";

import glassImg1 from "../../assets/images/products/glasses/aviator_metal_glasses.jpg";
import glassImg2 from "../../assets/images/products/glasses/black_square_frames.jpeg";
import glassImg3 from "../../assets/images/products/glasses/blue_light_glasses.jpg";
import glassImg4 from "../../assets/images/products/glasses/retro_round_glasses.jpg";
import glassImg5 from "../../assets/images/products/glasses/polarized_sunglasses.jpg";
import glassImg6 from "../../assets/images/products/glasses/oversized_brown_frames.webp";
import glassImg7 from "../../assets/images/products/glasses/tortoise_shell_glasses.webp";
import glassImg8 from "../../assets/images/products/glasses/gradient_lens_shades.webp";
import glassImg9 from "../../assets/images/products/glasses/clear_lens_glasses.jpg";
import glassImg10 from "../../assets/images/products/glasses/mirrored_aviator_shades.webp";

import shoeImg1 from "../../assets/images/products/shoes/classic_white_sneakers.webp";
import shoeImg2 from "../../assets/images/products/shoes/leather_dress_shoes.webp";
import shoeImg3 from "../../assets/images/products/shoes/running_trail_shoes.jpg";
import shoeImg4 from "../../assets/images/products/shoes/suede_loafer_shoes.webp";
import shoeImg5 from "../../assets/images/products/shoes/waterproof_hiking_boots.webp";
import shoeImg6 from "../../assets/images/products/shoes/high-top_canvas_shoes.webp";
import shoeImg7 from "../../assets/images/products/shoes/slip-on_casual_shoes.webp";
import shoeImg8 from "../../assets/images/products/shoes/breathable_running_shoes.webp";
import shoeImg9 from "../../assets/images/products/shoes/casual_leather_moccasins.jpg";
import shoeImg10 from "../../assets/images/products/shoes/faux_fur_winter_boots.jpg";

import hoodieImg1 from "../../assets/images/products/hoodies/black_zip-up_hoodie.jpg";
import hoodieImg2 from "../../assets/images/products/hoodies/oversized_grey_hoodie.jpg";
import hoodieImg3 from "../../assets/images/products/hoodies/fleece_lined_hoodie.jpg";
import hoodieImg4 from "../../assets/images/products/hoodies/graphic_print_hoodie.jpg";
import hoodieImg5 from "../../assets/images/products/hoodies/camo_pullover_hoodie.jpg";
import hoodieImg6 from "../../assets/images/products/hoodies/navy_blue_hoodie.jpg";
import hoodieImg7 from "../../assets/images/products/hoodies/colorblock_hoodie.jpg";
import hoodieImg8 from "../../assets/images/products/hoodies/lightweight_cotton_hoodie.jpg";
import hoodieImg9 from "../../assets/images/products/hoodies/maroon_athletic_hoodie.jpg";
import hoodieImg10 from "../../assets/images/products/hoodies/plaid_lined_hoodie.jpg";

import mobileImg1 from "../../assets/images/products/mobilephones/galaxy_Z_fold.jpg";
import mobileImg2 from "../../assets/images/products/mobilephones/iPhone_14_pro_max.jpeg";
import mobileImg3 from "../../assets/images/products/mobilephones/pixel_7_pro.jpg";
import mobileImg4 from "../../assets/images/products/mobilephones/OnePlus_10_pro.jpg";
import mobileImg5 from "../../assets/images/products/mobilephones/redmi_note_11.jpg";
import mobileImg6 from "../../assets/images/products/mobilephones/oppo_find_X5.jpg";
import mobileImg7 from "../../assets/images/products/mobilephones/sony_xperia_5.jpg";
import mobileImg8 from "../../assets/images/products/mobilephones/moto_edge_plus.jpg";
import mobileImg9 from "../../assets/images/products/mobilephones/asus_ROG_phone.webp";
import mobileImg10 from "../../assets/images/products/mobilephones/realme_GT_master.jpg";

import laptopImg1 from "../../assets/images/products/laptops/MacBook_pro_16.webp";
import laptopImg2 from "../../assets/images/products/laptops/dell_XPS_13.jpg";
import laptopImg3 from "../../assets/images/products/laptops/lenovo_ThinkPad_X1.webp";
import laptopImg4 from "../../assets/images/products/laptops/hp_spectre_x360.jpg";
import laptopImg5 from "../../assets/images/products/laptops/asus_ZenBook_duo.jpg";
import laptopImg6 from "../../assets/images/products/laptops/acer_predator_helios.jpg";
import laptopImg7 from "../../assets/images/products/laptops/microsoft_surface_pro.jpg";
import laptopImg8 from "../../assets/images/products/laptops/MSI_creator_z16.jpg";
import laptopImg9 from "../../assets/images/products/laptops/razer_blade_15.jpeg";
import laptopImg10 from "../../assets/images/products/laptops/samsung_galaxy_book.jpg";



const productsData = [
    //? Watches
    {
        "id": 1,
        "title": "Elegant Black Watch",
        "description": "This sleek, minimalist watch features a black leather strap, perfect for formal events or everyday wear. Its stainless steel case and precise quartz movement ensure durability and accuracy. Water-resistant up to 30 meters, with a date display and adjustable clasp for added convenience.",
        "originalPrice": 120,
        "discountedPrice": 88.38,
        "totalPrice": 88.38,
        "rating": 0,
        "usersRatings": [],
        "category": "Watches",
        "image": watchImg1,
        "quantity": 1,
        "brand": "Rolex",
        "condition": "Brand new",
        "isSaved": false,
        "features": [
            "Up to 50 meters, suitable for swimming and light snorkeling.",
            "Durable and rust-resistant, with a polished finish.",
            "Up to 2 years of battery life on a single charge.",
            "Glow-in-the-dark feature for easy time reading at night."
        ],
    },
    {
        "id": 2,
        "title": "Classic Silver Watch",
        "description": "Timeless design meets durability in this classic silver watch. Its stainless steel band and water-resistant construction make it perfect for daily wear. Features a date display, adjustable clasp, and luminous hands for enhanced visibility.",
        "originalPrice": 85,
        "discountedPrice": 59.72,
        "totalPrice": 59.72,
        "rating": 0,
        "usersRatings": [],
        "category": "Watches",
        "image": watchImg2,
        "quantity": 1,
        "brand": "Rolex",
        "condition": "Old items",
        "isSaved": false,
        "features": [
            "Up to 50 meters, suitable for swimming and light snorkeling.",
            "Durable and rust-resistant, with a polished finish.",
            "Up to 2 years of battery life on a single charge.",
            "Glow-in-the-dark feature for easy time reading at night."
        ],
    },
    {
        "id": 3,
        "title": "Sporty Digital Watch",
        "description": "Stay active with this water-resistant digital watch, featuring a backlight, stopwatch, alarm, and timer. Perfect for athletes and outdoor enthusiasts, with a battery life of up to 2 years and replaceable battery.",
        "originalPrice": 65,
        "discountedPrice": 44.29,
        "totalPrice": 44.29,
        "rating": 0,
        "usersRatings": [],
        "category": "Watches",
        "image": watchImg3,
        "quantity": 1,
        "brand": "Rolex",
        "condition": "Refurbished",
        "isSaved": false,
        "features": [
            "Up to 50 meters, suitable for swimming and light snorkeling.",
            "Durable and rust-resistant, with a polished finish.",
            "Up to 2 years of battery life on a single charge.",
            "Glow-in-the-dark feature for easy time reading at night."
        ],
    },
    {
        "id": 4,
        "title": "Gold Luxe Watch",
        "description": "Elevate your style with this luxurious gold-plated wristwatch, featuring Roman numerals and a sleek leather strap. Suitable for formal events and special occasions, with a precise quartz movement and water resistance up to 50 meters.",
        "originalPrice": 150,
        "discountedPrice": 108.29,
        "totalPrice": 108.29,
        "rating": 0,
        "usersRatings": [],
        "category": "Watches",
        "image": watchImg4,
        "quantity": 1,
        "brand": "Patek",
        "condition": "Brand new",
        "isSaved": false,
        "features": [
            "Up to 50 meters, suitable for swimming and light snorkeling.",
            "Durable and rust-resistant, with a polished finish.",
            "Up to 2 years of battery life on a single charge.",
            "Glow-in-the-dark feature for easy time reading at night."
        ],
    },
    {
        "id": 5,
        "title": "Leather Strap Watch",
        "description": "Combine elegance and comfort with this watch's brown leather strap and silver accents. Perfect for business casual or everyday wear, with a date display, adjustable clasp, and water resistance up to 50 meters.",
        "originalPrice": 100,
        "discountedPrice": 72.48,
        "totalPrice": 72.48,
        "rating": 0,
        "usersRatings": [],
        "category": "Watches",
        "image": watchImg5,
        "quantity": 1,
        "brand": "Patek",
        "condition": "Old items",
        "isSaved": false,
        "features": [
            "Up to 50 meters, suitable for swimming and light snorkeling.",
            "Durable and rust-resistant, with a polished finish.",
            "Up to 2 years of battery life on a single charge.",
            "Glow-in-the-dark feature for easy time reading at night."
        ],
    },
    {
        "id": 6,
        "title": "Smart Fitness Watch",
        "description": "Track your fitness goals with this watch, featuring heart rate monitoring, step tracking, notification alerts, and GPS tracking. Compatible with iOS and Android devices, with a battery life of up to 5 days.",
        "originalPrice": 130,
        "discountedPrice": 80.24,
        "totalPrice": 80.24,
        "rating": 0,
        "usersRatings": [],
        "category": "Watches",
        "image": watchImg6,
        "quantity": 1,
        "brand": "Patek",
        "condition": "Refurbished",
        "isSaved": false,
        "features": [
            "Up to 50 meters, suitable for swimming and light snorkeling.",
            "Durable and rust-resistant, with a polished finish.",
            "Up to 2 years of battery life on a single charge.",
            "Glow-in-the-dark feature for easy time reading at night."
        ],
    },
    {
        "id": 7,
        "title": "Vintage Style Watch",
        "description": "Classic analog design meets modern functionality in this vintage-style watch. Features a date display, luminous hands, leather strap, and water resistance up to 30 meters. Perfect for those who appreciate timeless elegance.",
        "originalPrice": 90,
        "discountedPrice": 59.13,
        "totalPrice": 59.13,
        "rating": 0,
        "usersRatings": [],
        "category": "Watches",
        "image": watchImg7,
        "quantity": 1,
        "brand": "Philippe",
        "condition": "Brand new",
        "isSaved": false,
        "features": [
            "Up to 50 meters, suitable for swimming and light snorkeling.",
            "Durable and rust-resistant, with a polished finish.",
            "Up to 2 years of battery life on a single charge.",
            "Glow-in-the-dark feature for easy time reading at night."
        ],
    },
    {
        "id": 8,
        "title": "Blue Dial Watch",
        "description": "Make a statement with this watch's striking blue face and luminous hands. Stainless steel case and water-resistant construction ensure durability, with a date display and adjustable clasp.",
        "originalPrice": 110,
        "discountedPrice": 70.87,
        "totalPrice": 70.87,
        "rating": 0,
        "usersRatings": [],
        "category": "Watches",
        "image": watchImg8,
        "quantity": 1,
        "brand": "Philippe",
        "condition": "Old items",
        "isSaved": false,
        "features": [
            "Up to 50 meters, suitable for swimming and light snorkeling.",
            "Durable and rust-resistant, with a polished finish.",
            "Up to 2 years of battery life on a single charge.",
            "Glow-in-the-dark feature for easy time reading at night."
        ],
    },
    {
        "id": 9,
        "title": "Rose Gold Watch",
        "description": "Add a touch of elegance with this rose gold-tone watch, featuring a crystal bezel, leather strap, and precise quartz movement. Suitable for formal events and special occasions, with water resistance up to 50 meters.",
        "originalPrice": 140,
        "discountedPrice": 104.25,
        "totalPrice": 104.25,
        "rating": 0,
        "usersRatings": [],
        "category": "Watches",
        "image": watchImg9,
        "quantity": 1,
        "brand": "Philippe",
        "condition": "Refurbished",
        "isSaved": false,
        "features": [
            "Up to 50 meters, suitable for swimming and light snorkeling.",
            "Durable and rust-resistant, with a polished finish.",
            "Up to 2 years of battery life on a single charge.",
            "Glow-in-the-dark feature for easy time reading at night."
        ],
    },
    {
        "id": 10,
        "title": "Apple Watch Ultra 2 Black AKrales",
        "description": "The ultimate adventure smartwatch, featuring a rugged black titanium case, Apple's brightest-ever display (up to 3000 nits), and advanced health and fitness tracking. Powered by the S9 SiP for lightning-fast performance and multi-day battery life, it's water-resistant to 100m and packed with safety features.",
        "originalPrice": 899,
        "discountedPrice": 551.46,
        "totalPrice": 551.46,
        "rating": 0,
        "usersRatings": [],
        "category": "Watches",
        "image": watchImg10,
        "quantity": 1,
        "brand": "Apple",
        "condition": "Brand new",
        "isSaved": false,
        "features": [
            "Up to 50 meters, suitable for swimming and light snorkeling.",
            "Durable and rust-resistant, with a polished finish.",
            "Up to 2 years of battery life on a single charge.",
            "Glow-in-the-dark feature for easy time reading at night."
        ],
    },

    // //? Glasses
    {
        "id": 11,
        "title": "Aviator Metal Glasses",
        "description": "Classic aviator design with durable metal frames, suitable for both men and women. Features adjustable nose pads and temple tips for comfort, along with scratch-resistant lenses. Lens width: 58mm, frame material: stainless steel.",
        "originalPrice": 50,
        "discountedPrice": 29.4,
        "totalPrice": 29.4,
        "rating": 0,
        "usersRatings": [],
        "category": "Glasses",
        "image": glassImg1,
        "quantity": 1,
        "brand": "Burberry",
        "condition": "Brand new",
        "isSaved": false,
        "features": [
            "Shields your eyes from harmful UVA and UVB rays.",
            "Durable lenses that resist daily wear and tear.",
            "Made with comfort-focused materials for all-day use.",
            "Stylish and versatile for both men and women."
        ],
    },
    {
        "id": 12,
        "title": "Black Square Frames",
        "description": "Sleek black square frames perfect for a modern, minimalist look. Made from high-quality acetate for durability and flexibility. Frame width: 48mm, lens material: polycarbonate.",
        "originalPrice": 45,
        "discountedPrice": 29.08,
        "totalPrice": 29.08,
        "rating": 0,
        "usersRatings": [],
        "category": "Glasses",
        "image": glassImg2,
        "quantity": 1,
        "brand": "Burberry",
        "condition": "Old items",
        "isSaved": false,
        "features": [
            "Shields your eyes from harmful UVA and UVB rays.",
            "Durable lenses that resist daily wear and tear.",
            "Made with comfort-focused materials for all-day use.",
            "Stylish and versatile for both men and women."
        ],
    },
    {
        "id": 13,
        "title": "Blue Light Glasses",
        "description": "Protect your eyes from digital screens with these blue light blocking glasses. Ideal for computer users and gamers, featuring anti-glare coating and UV protection. Lens width: 50mm, frame material: TR-90.",
        "originalPrice": 30,
        "discountedPrice": 21.07,
        "totalPrice": 21.07,
        "rating": 0,
        "usersRatings": [],
        "category": "Glasses",
        "image": glassImg3,
        "quantity": 1,
        "brand": "Burberry",
        "condition": "Refurbished",
        "isSaved": false,
        "features": [
            "Shields your eyes from harmful UVA and UVB rays.",
            "Durable lenses that resist daily wear and tear.",
            "Made with comfort-focused materials for all-day use.",
            "Stylish and versatile for both men and women."
        ],
    },
    {
        "id": 14,
        "title": "Retro Round Glasses",
        "description": "Round frames with a vintage vibe, inspired by classic designs. Suitable for both men and women, featuring adjustable nose pads and temple tips. Lens width: 52mm, frame material: acetate.",
        "originalPrice": 40,
        "discountedPrice": 28.01,
        "totalPrice": 28.01,
        "rating": 0,
        "usersRatings": [],
        "category": "Glasses",
        "image": glassImg4,
        "quantity": 1,
        "brand": "Gucci",
        "condition": "Brand new",
        "isSaved": false,
        "features": [
            "Shields your eyes from harmful UVA and UVB rays.",
            "Durable lenses that resist daily wear and tear.",
            "Made with comfort-focused materials for all-day use.",
            "Stylish and versatile for both men and women."
        ],
    },
    {
        "id": 15,
        "title": "Polarized Sunglasses",
        "description": "Stylish polarized lenses reduce glare from reflective surfaces. Perfect for driving, fishing, or outdoor activities, featuring scratch-resistant coating and UV protection. Lens width: 62mm, frame material: stainless steel.",
        "originalPrice": 60,
        "discountedPrice": 43.55,
        "totalPrice": 43.55,
        "rating": 0,
        "usersRatings": [],
        "category": "Glasses",
        "image": glassImg5,
        "quantity": 1,
        "brand": "Gucci",
        "condition": "Old items",
        "isSaved": false,
        "features": [
            "Shields your eyes from harmful UVA and UVB rays.",
            "Durable lenses that resist daily wear and tear.",
            "Made with comfort-focused materials for all-day use.",
            "Stylish and versatile for both men and women."
        ],
    },
    {
        "id": 16,
        "title": "Oversized Brown Frames",
        "description": "Fashionable oversized frames with a warm brown tint. Adds a touch of elegance to any outfit, featuring adjustable nose pads and temple tips. Lens width: 54mm, frame material: acetate.",
        "originalPrice": 55,
        "discountedPrice": 38.74,
        "totalPrice": 38.74,
        "rating": 0,
        "usersRatings": [],
        "category": "Glasses",
        "image": glassImg6,
        "quantity": 1,
        "brand": "Gucci",
        "condition": "Refurbished",
        "isSaved": false,
        "features": [
            "Shields your eyes from harmful UVA and UVB rays.",
            "Durable lenses that resist daily wear and tear.",
            "Made with comfort-focused materials for all-day use.",
            "Stylish and versatile for both men and women."
        ],
    },
    {
        "id": 17,
        "title": "Tortoise Shell Glasses",
        "description": "Trendy tortoise shell pattern on lightweight frames. Suitable for daily wear, featuring anti-glare coating and UV protection. Lens width: 50mm, frame material: TR-90.",
        "originalPrice": 35,
        "discountedPrice": 20.55,
        "totalPrice": 20.55,
        "rating": 0,
        "usersRatings": [],
        "category": "Glasses",
        "image": glassImg7,
        "quantity": 1,
        "brand": "Persol",
        "condition": "Brand new",
        "isSaved": false,
        "features": [
            "Shields your eyes from harmful UVA and UVB rays.",
            "Durable lenses that resist daily wear and tear.",
            "Made with comfort-focused materials for all-day use.",
            "Stylish and versatile for both men and women."
        ],
    },
    {
        "id": 18,
        "title": "Gradient Lens Shades",
        "description": "Gradient lenses add a stylish touch to these sleek metal frames. Perfect for fashion enthusiasts, featuring scratch-resistant coating and UV protection. Lens width: 58mm, frame material: stainless steel.",
        "originalPrice": 70,
        "discountedPrice": 48.34,
        "totalPrice": 48.34,
        "rating": 0,
        "usersRatings": [],
        "category": "Glasses",
        "image": glassImg8,
        "quantity": 1,
        "brand": "Persol",
        "condition": "Old items",
        "isSaved": false,
        "features": [
            "Shields your eyes from harmful UVA and UVB rays.",
            "Durable lenses that resist daily wear and tear.",
            "Made with comfort-focused materials for all-day use.",
            "Stylish and versatile for both men and women."
        ],
    },
    {
        "id": 19,
        "title": "Clear Lens Glasses",
        "description": "Minimalistic frames with clear lenses for a modern, minimalist look. Suitable for both men and women, featuring adjustable nose pads and temple tips. Lens width: 48mm, frame material: acetate.",
        "originalPrice": 25,
        "discountedPrice": 15.68,
        "totalPrice": 15.68,
        "rating": 0,
        "usersRatings": [],
        "category": "Glasses",
        "image": glassImg9,
        "quantity": 1,
        "brand": "Persol",
        "condition": "Refurbished",
        "isSaved": false,
        "features": [
            "Shields your eyes from harmful UVA and UVB rays.",
            "Durable lenses that resist daily wear and tear.",
            "Made with comfort-focused materials for all-day use.",
            "Stylish and versatile for both men and women."
        ],
    },
    {
        "id": 20,
        "title": "Mirrored Aviator Shades",
        "description": "Reflective mirrored lenses in a classic aviator style. Adds a touch of glamour to any outfit, featuring scratch-resistant coating and UV protection. Lens width: 62mm, frame material: stainless steel.",
        "originalPrice": 65,
        "discountedPrice": 40.24,
        "totalPrice": 40.24,
        "rating": 0,
        "usersRatings": [],
        "category": "Glasses",
        "image": glassImg10,
        "quantity": 1,
        "brand": "Persol",
        "condition": "Brand new",
        "isSaved": false,
        "features": [
            "Shields your eyes from harmful UVA and UVB rays.",
            "Durable lenses that resist daily wear and tear.",
            "Made with comfort-focused materials for all-day use.",
            "Stylish and versatile for both men and women."
        ],
    },

    // //? Shoes
    {
        "id": 21,
        "title": "Classic White Sneakers",
        "description": "Timeless and versatile, these comfortable white sneakers are perfect for everyday wear. Featuring breathable mesh panels, cushioned insoles, and durable rubber outsoles. Heel-to-toe length: 10 inches, weight: 12 oz.",
        "originalPrice": 75,
        "discountedPrice": 53.57,
        "totalPrice": 53.57,
        "rating": 0,
        "usersRatings": [],
        "category": "Shoes",
        "image": shoeImg1,
        "quantity": 1,
        "brand": "Nike",
        "condition": "Brand new",
        "isSaved": false,
        "features": [
            "Promotes airflow to keep feet cool and dry.",
            "Enhanced cushioning for all-day comfort.",
            "Provides excellent grip on multiple surfaces.",
            "Modern look suitable for both casual and athletic wear."
        ],
    },
    {
        "id": 22,
        "title": "Leather Dress Shoes",
        "description": "Elevate your formal style with these elegant black leather shoes. Handcrafted with premium leather, featuring a sleek design and comfortable fit. Heel-to-toe length: 11 inches, weight: 14 oz.",
        "originalPrice": 120,
        "discountedPrice": 86.37,
        "totalPrice": 86.37,
        "rating": 0,
        "usersRatings": [],
        "category": "Shoes",
        "image": shoeImg2,
        "quantity": 1,
        "brand": "Nike",
        "condition": "Old items",
        "isSaved": false,
        "features": [
            "Promotes airflow to keep feet cool and dry.",
            "Enhanced cushioning for all-day comfort.",
            "Provides excellent grip on multiple surfaces.",
            "Modern look suitable for both casual and athletic wear."
        ],
    },
    {
        "id": 23,
        "title": "Running Trail Shoes",
        "description": "Conquer rugged trails with these durable running shoes. Featuring aggressive tread patterns, breathable mesh uppers, and supportive ankle collars. Weight: 11 oz, heel-to-toe drop: 8mm.",
        "originalPrice": 90,
        "discountedPrice": 53.33,
        "totalPrice": 53.33,
        "rating": 0,
        "usersRatings": [],
        "category": "Shoes",
        "image": shoeImg3,
        "quantity": 1,
        "brand": "Nike",
        "condition": "Refurbished",
        "isSaved": false,
        "features": [
            "Promotes airflow to keep feet cool and dry.",
            "Enhanced cushioning for all-day comfort.",
            "Provides excellent grip on multiple surfaces.",
            "Modern look suitable for both casual and athletic wear."
        ],
    },
    {
        "id": 24,
        "title": "Suede Loafer Shoes",
        "description": "Step up your style with these stylish loafers made from soft suede. Slip-on design, breathable lining, and cushioned insoles ensure comfort. Heel-to-toe length: 10 inches, weight: 10 oz.",
        "originalPrice": 85,
        "discountedPrice": 53.87,
        "totalPrice": 53.87,
        "rating": 0,
        "usersRatings": [],
        "category": "Shoes",
        "image": shoeImg4,
        "quantity": 1,
        "brand": "Adidas",
        "condition": "Brand new",
        "isSaved": false,
        "features": [
            "Promotes airflow to keep feet cool and dry.",
            "Enhanced cushioning for all-day comfort.",
            "Provides excellent grip on multiple surfaces.",
            "Modern look suitable for both casual and athletic wear."
        ],
    },
    {
        "id": 25,
        "title": "Waterproof Hiking Boots",
        "description": "Tackle tough terrain and wet conditions with confidence. These boots feature waterproof membranes, breathable mesh panels, and aggressive tread patterns. Weight: 2 lbs, heel-to-toe length: 12 inches.",
        "originalPrice": 140,
        "discountedPrice": 97.46,
        "totalPrice": 97.46,
        "rating": 0,
        "usersRatings": [],
        "category": "Shoes",
        "image": shoeImg5,
        "quantity": 1,
        "brand": "Adidas",
        "condition": "Old items",
        "isSaved": false,
        "features": [
            "Promotes airflow to keep feet cool and dry.",
            "Enhanced cushioning for all-day comfort.",
            "Provides excellent grip on multiple surfaces.",
            "Modern look suitable for both casual and athletic wear."
        ],
    },
    {
        "id": 26,
        "title": "High-Top Canvas Shoes",
        "description": "Rock a classic look with these iconic high-top sneakers. Durable canvas uppers, breathable mesh lining, and rubber outsoles ensure comfort and style. Heel-to-toe length: 11 inches, weight: 14 oz.",
        "originalPrice": 65,
        "discountedPrice": 40.62,
        "totalPrice": 40.62,
        "rating": 0,
        "usersRatings": [],
        "category": "Shoes",
        "image": shoeImg6,
        "quantity": 1,
        "brand": "Adidas",
        "condition": "Refurbished",
        "isSaved": false,
        "features": [
            "Promotes airflow to keep feet cool and dry.",
            "Enhanced cushioning for all-day comfort.",
            "Provides excellent grip on multiple surfaces.",
            "Modern look suitable for both casual and athletic wear."
        ],
    },
    {
        "id": 27,
        "title": "Slip-On Casual Shoes",
        "description": "Simplify your daily routine with these easy-to-wear slip-on shoes. Soft leather uppers, breathable lining, and cushioned insoles provide comfort. Heel-to-toe length: 10 inches, weight: 9 oz.",
        "originalPrice": 50,
        "discountedPrice": 36.73,
        "totalPrice": 36.73,
        "rating": 0,
        "usersRatings": [],
        "category": "Shoes",
        "image": shoeImg7,
        "quantity": 1,
        "brand": "Puma",
        "condition": "Brand new",
        "isSaved": false,
        "features": [
            "Promotes airflow to keep feet cool and dry.",
            "Enhanced cushioning for all-day comfort.",
            "Provides excellent grip on multiple surfaces.",
            "Modern look suitable for both casual and athletic wear."
        ],
    },
    {
        "id": 28,
        "title": "Breathable Running Shoes",
        "description": "Maximize performance with these lightweight running shoes featuring mesh uppers, supportive midsoles, and grippy outsoles. Weight: 9 oz, heel-to-toe drop: 10mm.",
        "originalPrice": 85,
        "discountedPrice": 53.43,
        "totalPrice": 53.43,
        "rating": 0,
        "usersRatings": [],
        "category": "Shoes",
        "image": shoeImg8,
        "quantity": 1,
        "brand": "Puma",
        "condition": "Old items",
        "isSaved": false,
        "features": [
            "Promotes airflow to keep feet cool and dry.",
            "Enhanced cushioning for all-day comfort.",
            "Provides excellent grip on multiple surfaces.",
            "Modern look suitable for both casual and athletic wear."
        ],
    },
    {
        "id": 29,
        "title": "Casual Leather Moccasins",
        "description": "Elevate daily style with these comfortable leather moccasins. Soft leather uppers, breathable lining, and cushioned insoles ensure comfort. Heel-to-toe length: 10 inches, weight: 12 oz.",
        "originalPrice": 95,
        "discountedPrice": 65.82,
        "totalPrice": 65.82,
        "rating": 0,
        "usersRatings": [],
        "category": "Shoes",
        "image": shoeImg9,
        "quantity": 1,
        "brand": "Puma",
        "condition": "Refurbished",
        "isSaved": false,
        "features": [
            "Promotes airflow to keep feet cool and dry.",
            "Enhanced cushioning for all-day comfort.",
            "Provides excellent grip on multiple surfaces.",
            "Modern look suitable for both casual and athletic wear."
        ],
    },
    {
        "id": 30,
        "title": "Faux Fur Winter Boots",
        "description": "Stay warm and stylish with these insulated winter boots lined with faux fur. Waterproof membranes, breathable mesh panels, and grippy outsoles. Weight: 2.5 lbs, heel-to-toe length: 13 inches.",
        "originalPrice": 130,
        "discountedPrice": 90.42,
        "totalPrice": 90.42,
        "rating": 0,
        "usersRatings": [],
        "category": "Shoes",
        "image": shoeImg10,
        "quantity": 1,
        "brand": "Puma",
        "condition": "Brand new",
        "isSaved": false,
        "features": [
            "Promotes airflow to keep feet cool and dry.",
            "Enhanced cushioning for all-day comfort.",
            "Provides excellent grip on multiple surfaces.",
            "Modern look suitable for both casual and athletic wear."
        ],
    },

    // //? Hoodies
    {
        "id": 31,
        "title": "Black Zip-Up Hoodie",
        "description": "Stay cozy with this soft black hoodie featuring a front zipper and adjustable drawstrings. Made from premium cotton blend for comfort and durability. Fit: regular, fabric thickness: 280gsm.",
        "originalPrice": 60,
        "discountedPrice": 41.58,
        "totalPrice": 41.58,
        "rating": 0,
        "usersRatings": [],
        "category": "Hoodies",
        "image": hoodieImg1,
        "quantity": 1,
        "brand": "Nike",
        "condition": "Brand new",
        "isSaved": false,
        "features": [
            "Soft, breathable fabric with a comfortable fleece lining.",
            "Customize your fit for added warmth and style.",
            "Front pocket for hand warmth and storage.",
            "Maintains size and shape even after multiple washes."
        ],
    },
    {
        "id": 32,
        "title": "Oversized Grey Hoodie",
        "description": "Lounging just got comfier with this oversized grey hoodie. Features a relaxed fit, soft fleece lining, and kangaroo pockets for convenience. Fabric: 80% cotton, 20% polyester.",
        "originalPrice": 45,
        "discountedPrice": 26.53,
        "totalPrice": 26.53,
        "rating": 0,
        "usersRatings": [],
        "category": "Hoodies",
        "image": hoodieImg2,
        "quantity": 1,
        "brand": "Nike",
        "condition": "Old items",
        "isSaved": false,
        "features": [
            "Soft, breathable fabric with a comfortable fleece lining.",
            "Customize your fit for added warmth and style.",
            "Front pocket for hand warmth and storage.",
            "Maintains size and shape even after multiple washes."
        ],
    },
    {
        "id": 33,
        "title": "Fleece Lined Hoodie",
        "description": "Brave the cold with this cozy fleece-lined hoodie. Thick, plush fleece traps warmth, while the durable outer shell withstands harsh weather. Weight: 400gsm.",
        "originalPrice": 55,
        "discountedPrice": 36.75,
        "totalPrice": 36.75,
        "rating": 0,
        "usersRatings": [],
        "category": "Hoodies",
        "image": hoodieImg3,
        "quantity": 1,
        "brand": "Nike",
        "condition": "Refurbished",
        "isSaved": false,
        "features": [
            "Soft, breathable fabric with a comfortable fleece lining.",
            "Customize your fit for added warmth and style.",
            "Front pocket for hand warmth and storage.",
            "Maintains size and shape even after multiple washes."
        ],
    },
    {
        "id": 34,
        "title": "Graphic Print Hoodie",
        "description": "Make a statement with this stylish hoodie featuring bold graphic prints. Printed with eco-friendly ink, this hoodie combines fashion and sustainability. Fit: slim, fabric: 100% cotton.",
        "originalPrice": 50,
        "discountedPrice": 30.35,
        "totalPrice": 30.35,
        "rating": 0,
        "usersRatings": [],
        "category": "Hoodies",
        "image": hoodieImg4,
        "quantity": 1,
        "brand": "Adidas",
        "condition": "Brand new",
        "isSaved": false,
        "features": [
            "Soft, breathable fabric with a comfortable fleece lining.",
            "Customize your fit for added warmth and style.",
            "Front pocket for hand warmth and storage.",
            "Maintains size and shape even after multiple washes."
        ],
    },
    {
        "id": 35,
        "title": "Camo Pullover Hoodie",
        "description": "Blend in or stand out with this camouflage print hoodie. Kangaroo pockets and adjustable drawstrings add functionality. Fabric: 60% cotton, 40% polyester.",
        "originalPrice": 65,
        "discountedPrice": 45.23,
        "totalPrice": 45.23,
        "rating": 0,
        "usersRatings": [],
        "category": "Hoodies",
        "image": hoodieImg5,
        "quantity": 1,
        "brand": "Adidas",
        "condition": "Old items",
        "isSaved": false,
        "features": [
            "Soft, breathable fabric with a comfortable fleece lining.",
            "Customize your fit for added warmth and style.",
            "Front pocket for hand warmth and storage.",
            "Maintains size and shape even after multiple washes."
        ],
    },
    {
        "id": 36,
        "title": "Navy Dark Blue Hoodie",
        "description": "Simple yet stylish, this navy blue hoodie features adjustable drawstrings and a classic fit. Suitable for daily wear or layering. Fabric: 80% cotton, 20% polyester.",
        "originalPrice": 40,
        "discountedPrice": 25.63,
        "totalPrice": 25.63,
        "rating": 0,
        "usersRatings": [],
        "category": "Hoodies",
        "image": hoodieImg6,
        "quantity": 1,
        "brand": "Adidas",
        "condition": "Refurbished",
        "isSaved": false,
        "features": [
            "Soft, breathable fabric with a comfortable fleece lining.",
            "Customize your fit for added warmth and style.",
            "Front pocket for hand warmth and storage.",
            "Maintains size and shape even after multiple washes."
        ],
    },
    {
        "id": 37,
        "title": "Colorblock Hoodie",
        "description": "Stay trendy with this colorblock hoodie featuring contrasting colors. Soft, breathable fabric and relaxed fit ensure comfort. Weight: 280gsm.",
        "originalPrice": 48,
        "discountedPrice": 26.87,
        "totalPrice": 26.87,
        "rating": 0,
        "usersRatings": [],
        "category": "Hoodies",
        "image": hoodieImg7,
        "quantity": 1,
        "brand": "Champion",
        "condition": "Brand new",
        "isSaved": false,
        "features": [
            "Soft, breathable fabric with a comfortable fleece lining.",
            "Customize your fit for added warmth and style.",
            "Front pocket for hand warmth and storage.",
            "Maintains size and shape even after multiple washes."
        ],
    },
    {
        "id": 38,
        "title": "Lightweight Cotton Hoodie",
        "description": "Perfect for layering, this lightweight cotton hoodie is a wardrobe essential. Soft, breathable fabric and adjustable drawstrings. Fabric: 100% cotton.",
        "originalPrice": 35,
        "discountedPrice": 25.04,
        "totalPrice": 25.04,
        "rating": 0,
        "usersRatings": [],
        "category": "Hoodies",
        "image": hoodieImg8,
        "quantity": 1,
        "brand": "Champion",
        "condition": "Old items",
        "isSaved": false,
        "features": [
            "Soft, breathable fabric with a comfortable fleece lining.",
            "Customize your fit for added warmth and style.",
            "Front pocket for hand warmth and storage.",
            "Maintains size and shape even after multiple washes."
        ],
    },
    {
        "id": 39,
        "title": "Maroon Athletic Hoodie",
        "description": "Take your workout to the next level with this athletic hoodie. Moisture-wicking fabric and breathable mesh panels ensure performance. Fit: slim, fabric: 90% polyester, 10% spandex.",
        "originalPrice": 55,
        "discountedPrice": 35.89,
        "totalPrice": 35.89,
        "rating": 0,
        "usersRatings": [],
        "category": "Hoodies",
        "image": hoodieImg9,
        "quantity": 1,
        "brand": "Champion",
        "condition": "Refurbished",
        "isSaved": false,
        "features": [
            "Soft, breathable fabric with a comfortable fleece lining.",
            "Customize your fit for added warmth and style.",
            "Front pocket for hand warmth and storage.",
            "Maintains size and shape even after multiple washes."
        ],
    },
    {
        "id": 40,
        "title": "Plaid Lined Hoodie",
        "description": "Add a touch of rustic charm with this plaid-lined hoodie. Soft fleece lining and durable outer shell provide warmth and comfort. Weight: 380gsm.",
        "originalPrice": 65,
        "discountedPrice": 47.7,
        "totalPrice": 47.7,
        "rating": 0,
        "usersRatings": [],
        "category": "Hoodies",
        "image": hoodieImg10,
        "quantity": 1,
        "brand": "Champion",
        "condition": "Brand new",
        "isSaved": false,
        "features": [
            "Soft, breathable fabric with a comfortable fleece lining.",
            "Customize your fit for added warmth and style.",
            "Front pocket for hand warmth and storage.",
            "Maintains size and shape even after multiple washes."
        ],
    },

    // //? Mobiles
    {
        "id": 41,
        "title": "Galaxy Z Fold",
        "description": "Experience the future of smartphones with Samsung's revolutionary foldable phone. Featuring a stunning 7.6-inch Dynamic AMOLED display, powerful Snapdragon 888 processor, and advanced multi-camera system. Enjoy seamless multitasking, immersive gaming, and cinematic entertainment. RAM: 12GB, storage: 512GB.",
        "originalPrice": 1800,
        "discountedPrice": 1402.04,
        "totalPrice": 1402.04,
        "rating": 0,
        "usersRatings": [],
        "category": "Mobilephones",
        "image": mobileImg1,
        "quantity": 1,
        "brand": "Samsung",
        "condition": "Brand new",
        "isSaved": false,
        "features": [
            "Crystal-clear 6.5” screen with vibrant colors and deep blacks.",
            "64MP main camera with ultra-wide and macro lenses.",
            "50% charge in just 30 minutes with included fast charger.",
            "Supports microSD cards up to 1TB."
        ],
    },
    {
        "id": 42,
        "title": "iPhone 14 Pro",
        "description": "Elevate your mobile experience with Apple's latest flagship. Boasting advanced quad-camera setup with Night mode, A16 Bionic chip, and stunning 6.1-inch Super Retina XDR display. Water-resistant, wireless charging, and iOS 16 operating system. RAM: 6GB, storage: 128GB.",
        "originalPrice": 1200,
        "discountedPrice": 815.75,
        "totalPrice": 815.75,
        "rating": 0,
        "usersRatings": [],
        "category": "Mobilephones",
        "image": mobileImg2,
        "quantity": 1,
        "brand": "Apple",
        "condition": "Old items",
        "isSaved": false,
        "features": [
            "Crystal-clear 6.5” screen with vibrant colors and deep blacks.",
            "64MP main camera with ultra-wide and macro lenses.",
            "50% charge in just 30 minutes with included fast charger.",
            "Supports microSD cards up to 1TB."
        ],
    },
    {
        "id": 43,
        "title": "Pixel 7 Pro",
        "description": "Capture life's moments with Google's smartphone featuring smart AI-powered camera software. Equipped with 6.7-inch OLED display, Snapdragon 888 processor, and timely software updates. Enjoy seamless Google ecosystem integration and intuitive interface. RAM: 12GB, storage: 256GB.",
        "originalPrice": 950,
        "discountedPrice": 693.55,
        "totalPrice": 693.55,
        "rating": 0,
        "usersRatings": [],
        "category": "Mobilephones",
        "image": mobileImg3,
        "quantity": 1,
        "brand": "Google",
        "condition": "Refurbished",
        "isSaved": false,
        "features": [
            "Crystal-clear 6.5” screen with vibrant colors and deep blacks.",
            "64MP main camera with ultra-wide and macro lenses.",
            "50% charge in just 30 minutes with included fast charger.",
            "Supports microSD cards up to 1TB."
        ],
    },
    {
        "id": 44,
        "title": "OnePlus 10 Pro",
        "description": "Unlock premium performance with OnePlus' flagship phone. Powered by Snapdragon 888, 6.7-inch AMOLED display, and rapid 80W fast charging. Experience OxygenOS, intuitive interface, and advanced camera capabilities. RAM: 8GB, storage: 128GB.",
        "originalPrice": 850,
        "discountedPrice": 579.4,
        "totalPrice": 579.4,
        "rating": 0,
        "usersRatings": [],
        "category": "Mobilephones",
        "image": mobileImg4,
        "quantity": 1,
        "brand": "OnePlus",
        "condition": "Brand new",
        "isSaved": false,
        "features": [
            "Crystal-clear 6.5” screen with vibrant colors and deep blacks.",
            "64MP main camera with ultra-wide and macro lenses.",
            "50% charge in just 30 minutes with included fast charger.",
            "Supports microSD cards up to 1TB."
        ],
    },
    {
        "id": 45,
        "title": "Redmi Note 11",
        "description": "Discover budget-friendly excellence with Redmi's feature-packed phone. Offering 6.5-inch HD+ display, Snapdragon 680 processor, and impressive 50MP camera. Long-lasting 5000mAh battery, dual-SIM support, and MIUI 13 operating system. RAM: 4GB, storage: 64GB.",
        "originalPrice": 350,
        "discountedPrice": 255.67,
        "totalPrice": 255.67,
        "rating": 0,
        "usersRatings": [],
        "category": "Mobilephones",
        "image": mobileImg5,
        "quantity": 1,
        "brand": "Xiaomi",
        "condition": "Brand new",
        "isSaved": false,
        "features": [
            "Crystal-clear 6.5” screen with vibrant colors and deep blacks.",
            "64MP main camera with ultra-wide and macro lenses.",
            "50% charge in just 30 minutes with included fast charger.",
            "Supports microSD cards up to 1TB."
        ],
    },
    {
        "id": 46,
        "title": "Oppo Find X5",
        "description": "Unleash photography potential with Oppo's flagship phone. Featuring 6.7-inch AMOLED display, Snapdragon 888 processor, and revolutionary 50MP camera system with 5G connectivity. SuperVOOC fast charging, waterproof design, and ColorOS 12 operating system. RAM: 8GB, storage: 256GB.",
        "originalPrice": 1000,
        "discountedPrice": 652.11,
        "totalPrice": 652.11,
        "rating": 0,
        "usersRatings": [],
        "category": "Mobilephones",
        "image": mobileImg6,
        "quantity": 1,
        "brand": "Oppo",
        "condition": "Old items",
        "isSaved": false,
        "features": [
            "Crystal-clear 6.5” screen with vibrant colors and deep blacks.",
            "64MP main camera with ultra-wide and macro lenses.",
            "50% charge in just 30 minutes with included fast charger.",
            "Supports microSD cards up to 1TB."
        ],
    },
    {
        "id": 47,
        "title": "Sony Xperia 5",
        "description": "Immerse yourself in entertainment with Sony's phone built for media enthusiasts. Boasting 6.1-inch 4K OLED display, Snapdragon 888 processor, and exceptional camera capabilities. Water-resistant, wireless charging, and Android 11 operating system. RAM: 8GB, storage: 128GB.",
        "originalPrice": 1100,
        "discountedPrice": 754.16,
        "totalPrice": 754.16,
        "rating": 0,
        "usersRatings": [],
        "category": "Mobilephones",
        "image": mobileImg7,
        "quantity": 1,
        "brand": "Sony",
        "condition": "Refurbished",
        "isSaved": false,
        "features": [
            "Crystal-clear 6.5” screen with vibrant colors and deep blacks.",
            "64MP main camera with ultra-wide and macro lenses.",
            "50% charge in just 30 minutes with included fast charger.",
            "Supports microSD cards up to 1TB."
        ],
    },
    {
        "id": 48,
        "title": "Moto Edge Plus",
        "description": "Experience Motorola's top-tier phone with 5G capability. Featuring 6.7-inch OLED display, Snapdragon 888 processor, and advanced triple-camera system. Enjoy near-stock Android experience, water-repellent design, and rapid 30W fast charging. RAM: 6GB, storage: 128GB.",
        "originalPrice": 900,
        "discountedPrice": 616.12,
        "totalPrice": 616.12,
        "rating": 0,
        "usersRatings": [],
        "category": "Mobilephones",
        "image": mobileImg8,
        "quantity": 1,
        "brand": "Motorola",
        "condition": "Brand new",
        "isSaved": false,
        "features": [
            "Crystal-clear 6.5” screen with vibrant colors and deep blacks.",
            "64MP main camera with ultra-wide and macro lenses.",
            "50% charge in just 30 minutes with included fast charger.",
            "Supports microSD cards up to 1TB."
        ],
    },
    {
        "id": 49,
        "title": "Asus ROG Phone",
        "description": "Dominate gaming with Asus' powerful phone featuring advanced cooling system. Equipped with 6.78-inch AMOLED display, Snapdragon 888 processor, and massive 6000mAh battery. Exclusive ROG UI, dual-SIM support, and 65W fast charging. RAM: 12GB, storage: 512GB.",
        "originalPrice": 1400,
        "discountedPrice": 914.94,
        "totalPrice": 914.94,
        "rating": 0,
        "usersRatings": [],
        "category": "Mobilephones",
        "image": mobileImg9,
        "quantity": 1,
        "brand": "Asus",
        "condition": "Old items",
        "isSaved": false,
        "features": [
            "Crystal-clear 6.5” screen with vibrant colors and deep blacks.",
            "64MP main camera with ultra-wide and macro lenses.",
            "50% charge in just 30 minutes with included fast charger.",
            "Supports microSD cards up to 1TB."
        ],
    },
    {
        "id": 50,
        "title": "Realme GT Master",
        "description": "Elevate gaming and style with Realme's sleek phone. Powered by Snapdragon 888, 6.43-inch Super AMOLED display, and 65W fast charging. Featuring 64MP primary camera, dual-SIM support, and Realme UI 2.0 operating system. RAM: 6GB, storage: 128GB.",
        "originalPrice": 600,
        "discountedPrice": 396.12,
        "totalPrice": 396.12,
        "rating": 0,
        "usersRatings": [],
        "category": "Mobilephones",
        "image": mobileImg10,
        "quantity": 1,
        "brand": "Realme",
        "condition": "Refurbished",
        "isSaved": false,
        "features": [
            "Crystal-clear 6.5” screen with vibrant colors and deep blacks.",
            "64MP main camera with ultra-wide and macro lenses.",
            "50% charge in just 30 minutes with included fast charger.",
            "Supports microSD cards up to 1TB."
        ],
    },

    // //? Laptops
    {
        "id": 51,
        "title": "MacBook Pro 16",
        "description": "Unlock unparalleled performance with Apple's MacBook Pro 16, powered by the revolutionary M1 chip. Features a stunning 16-inch Retina display, up to 16 hours of battery life, and seamless integration with other Apple devices. Storage: 512GB SSD, RAM: 16GB.",
        "originalPrice": 2500,
        "discountedPrice": 1558.56,
        "totalPrice": 1558.56,
        "rating": 0,
        "usersRatings": [],
        "category": "Laptops",
        "image": laptopImg1,
        "quantity": 1,
        "brand": "Apple",
        "condition": "Brand new",
        "isSaved": false,
        "features": [
            "High-performance CPU for multitasking and speed.",
            "Fast boot times and smooth performance for demanding tasks.",
            "15.6” screen with anti-glare coating and vivid color accuracy.",
            "Type comfortably in low-light environments."
        ],
    },
    {
        "id": 52,
        "title": "Dell XPS 13",
        "description": "Experience premium portability with Dell's ultra-thin XPS 13, boasting a breathtaking 4K display. Weighs just 2.7lbs, features 10th Gen Intel Core i7 processor, and up to 12 hours of battery life. Storage: 1TB SSD, RAM: 16GB.",
        "originalPrice": 1500,
        "discountedPrice": 1042.97,
        "totalPrice": 1042.97,
        "rating": 0,
        "usersRatings": [],
        "category": "Laptops",
        "image": laptopImg2,
        "quantity": 1,
        "brand": "Dell",
        "condition": "Old items",
        "isSaved": false,
        "features": [
            "High-performance CPU for multitasking and speed.",
            "Fast boot times and smooth performance for demanding tasks.",
            "15.6” screen with anti-glare coating and vivid color accuracy.",
            "Type comfortably in low-light environments."
        ],
    },
    {
        "id": 53,
        "title": "Lenovo ThinkPad X1",
        "description": "Built for business, Lenovo's ThinkPad X1 combines durability with exceptional performance. Features a 14-inch Full HD display, 11th Gen Intel Core i7 processor, and legendary ThinkPad keyboard. Storage: 512GB SSD, RAM: 16GB.",
        "originalPrice": 1800,
        "discountedPrice": 1250.31,
        "totalPrice": 1250.31,
        "rating": 0,
        "usersRatings": [],
        "category": "Laptops",
        "image": laptopImg3,
        "quantity": 1,
        "brand": "Lenovo",
        "condition": "Refurbished",
        "isSaved": false,
        "features": [
            "High-performance CPU for multitasking and speed.",
            "Fast boot times and smooth performance for demanding tasks.",
            "15.6” screen with anti-glare coating and vivid color accuracy.",
            "Type comfortably in low-light environments."
        ],
    },
    {
        "id": 54,
        "title": "HP Spectre x360",
        "description": "Elevate flexibility with HP's convertible Spectre x360, featuring a stunning 13.3-inch 4K touchscreen. Powered by 11th Gen Intel Core i7 processor, up to 22 hours of battery life, and gem-cut design. Storage: 1TB SSD, RAM: 16GB.",
        "originalPrice": 1600,
        "discountedPrice": 1023.02,
        "totalPrice": 1023.02,
        "rating": 0,
        "usersRatings": [],
        "category": "Laptops",
        "image": laptopImg4,
        "quantity": 1,
        "brand": "HP",
        "condition": "Brand new",
        "isSaved": false,
        "features": [
            "High-performance CPU for multitasking and speed.",
            "Fast boot times and smooth performance for demanding tasks.",
            "15.6” screen with anti-glare coating and vivid color accuracy.",
            "Type comfortably in low-light environments."
        ],
    },
    {
        "id": 55,
        "title": "Asus ZenBook Duo",
        "description": "Revolutionize multitasking with Asus' innovative ZenBook Duo, featuring dual 14-inch displays. Powered by 11th Gen Intel Core i7 processor, up to 17 hours of battery life, and extensive connectivity options. Storage: 1TB SSD, RAM: 16GB.",
        "originalPrice": 1900,
        "discountedPrice": 1105.65,
        "totalPrice": 1105.65,
        "rating": 0,
        "usersRatings": [],
        "category": "Laptops",
        "image": laptopImg5,
        "quantity": 1,
        "brand": "Asus",
        "condition": "Old items",
        "isSaved": false,
        "features": [
            "High-performance CPU for multitasking and speed.",
            "Fast boot times and smooth performance for demanding tasks.",
            "15.6” screen with anti-glare coating and vivid color accuracy.",
            "Type comfortably in low-light environments."
        ],
    },
    {
        "id": 56,
        "title": "Acer Predator Helios",
        "description": "Unleash gaming dominance with Acer's Predator Helios, powered by 11th Gen Intel Core i9 processor and NVIDIA GeForce RTX 3080 GPU. Features 15.6-inch 4K display, up to 4 hours of battery life, and customizable backlighting. Storage: 2TB SSD, RAM: 32GB.",
        "originalPrice": 2200,
        "discountedPrice": 1649.77,
        "totalPrice": 1649.77,
        "rating": 0,
        "usersRatings": [],
        "category": "Laptops",
        "image": laptopImg6,
        "quantity": 1,
        "brand": "Acer",
        "condition": "Refurbished",
        "isSaved": false,
        "features": [
            "High-performance CPU for multitasking and speed.",
            "Fast boot times and smooth performance for demanding tasks.",
            "15.6” screen with anti-glare coating and vivid color accuracy.",
            "Type comfortably in low-light environments."
        ],
    },
    {
        "id": 57,
        "title": "Microsoft Surface Pro",
        "description": "Transform productivity with Microsoft's versatile Surface Pro, featuring a 12.3-inch PixelSense touchscreen. Powered by 11th Gen Intel Core i7 processor, up to 11 hours of battery life, and seamless integration with Microsoft services. Storage: 512GB SSD, RAM: 16GB.",
        "originalPrice": 1400,
        "discountedPrice": 820.76,
        "totalPrice": 820.76,
        "rating": 0,
        "usersRatings": [],
        "category": "Laptops",
        "image": laptopImg7,
        "quantity": 1,
        "brand": "Microsoft",
        "condition": "Brand new",
        "isSaved": false,
        "features": [
            "High-performance CPU for multitasking and speed.",
            "Fast boot times and smooth performance for demanding tasks.",
            "15.6” screen with anti-glare coating and vivid color accuracy.",
            "Type comfortably in low-light environments."
        ],
    },
    {
        "id": 58,
        "title": "MSI Creator Z16",
        "description": "Bring creative visions to life with MSI's Creator Z16, featuring a stunning 16-inch 4K display. Powered by 11th Gen Intel Core i9 processor, NVIDIA GeForce RTX 3060 GPU, and extensive connectivity options. Storage: 2TB SSD, RAM: 32GB.",
        "originalPrice": 2100,
        "discountedPrice": 1528.61,
        "totalPrice": 1528.61,
        "rating": 0,
        "usersRatings": [],
        "category": "Laptops",
        "image": laptopImg8,
        "quantity": 1,
        "brand": "MSI",
        "condition": "Old items",
        "isSaved": false,
        "features": [
            "High-performance CPU for multitasking and speed.",
            "Fast boot times and smooth performance for demanding tasks.",
            "15.6” screen with anti-glare coating and vivid color accuracy.",
            "Type comfortably in low-light environments."
        ],
    },
    {
        "id": 59,
        "title": "Razer Blade 15",
        "description": "Experience gaming perfection with Razer's sleek Blade 15, powered by 11th Gen Intel Core i9 processor and NVIDIA GeForce RTX 3080 GPU. Features 15.6-inch 4K display, up to 6 hours of battery life, and customizable Chroma RGB lighting. Storage: 1TB SSD, RAM: 16GB.",
        "originalPrice": 2300,
        "discountedPrice": 1675.41,
        "totalPrice": 1675.41,
        "rating": 0,
        "usersRatings": [],
        "category": "Laptops",
        "image": laptopImg9,
        "quantity": 1,
        "brand": "Razer",
        "condition": "Refurbished",
        "isSaved": false,
        "features": [
            "High-performance CPU for multitasking and speed.",
            "Fast boot times and smooth performance for demanding tasks.",
            "15.6” screen with anti-glare coating and vivid color accuracy.",
            "Type comfortably in low-light environments."
        ],
    },
    {
        "id": 60,
        "title": "Samsung Galaxy Book",
        "description": "Discover lightweight productivity with Samsung's Galaxy Book, featuring a 13.3-inch Full HD display. Powered by 11th Gen Intel Core i5 processor, up to 14 hours of battery life, and seamless integration with Samsung devices. Storage: 256GB SSD, RAM: 8GB.",
        "originalPrice": 1300,
        "discountedPrice": 773.71,
        "totalPrice": 773.71,
        "rating": 0,
        "usersRatings": [],
        "category": "Laptops",
        "image": laptopImg10,
        "quantity": 1,
        "brand": "Samsung",
        "condition": "Brand new",
        "isSaved": false,
        "features": [
            "High-performance CPU for multitasking and speed.",
            "Fast boot times and smooth performance for demanding tasks.",
            "15.6” screen with anti-glare coating and vivid color accuracy.",
            "Type comfortably in low-light environments."
        ],
    },
];

export default productsData;